# -*- coding: utf-8 -*-
"""Copy of Soal FGD Pagi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RatV2K2ppZDl_Ljq7iECbAmGx7spPRWn

## No. 1

a = False
b = True
c = False
1. b and c
2. b or c
3. not a and b
4. (a and b) or not c
5. not b and not (a or c)
"""

a = False
b = True
c = False

print(b and c)
print(b or c)
print(not a and b)
print((a and b) or not c)
print(not b and not (a or c))

"""## No. 2
print(Hello!)
something == input('Enter something: )
print('You entered:' something)
"""

print('Hello!')
something = input('Enter something: ')
print('You entered: ', something)

"""## No. 3
print('Hello!')
something = input("Enter something: ")
if something = 'hello':
    print("Hello for you too!")

elif something = 'hi'
    print('Hi there!')
else:
    print("I don't know what," something, "means.")
"""

print('Hello!')

something = input("Enter something: ")
if something == 'hello':
    print("Hello for you too!")
elif something == 'hi':
    print('Hi there!')
else:
    print("I don't know what ", something, " means.")

"""## No. 4
Make something that asks the user to enter two words, and prints 1000 of each with spaces in between. For example, if the user enters hello and hi the program would print  : hello hi hello hi hello hi hello hi hello hi ...
"""

something = input("Enter something: ")
for i in range(100):
    print(something, end=' ')

"""## No. 5
Rock paper scissors

Tabel Kebenaran
![image.png](attachment:image.png)
"""

player1 = input("Player 1? ")
player2 = input("Plaer 2? ")

if(player1 == 'rock' and player2=='paper'):
    print("Player 2 wins!")

elif (player1 == 'rock' and player2=='scissor'):
    print("Player 1 wins!")

elif(player1 == 'paper' and player2=='rock'):
    print("Player 1 wins!")

elif (player1 == 'paper' and player2=='scissor'):
    print("Player 2 wins!")

elif(player1 == 'scissor' and player2=='rock'):
    print("Player 2 wins!")

elif (player1 == 'scissor' and player2=='paper'):
    print("Player 1 wins!")

elif (player1 == player2):
    print("Tie")

else:
    print("This is not a valid object selection")

"""## No. 6"""

while True:
  teks = input()
  if teks == "berhenti":
    break

"""## No. 7"""

while True:
  print("""
  MENU JAJANAN PASAR
  1. Donat - Rp 1250
  2. Bakwan - Rp 1000
  3. Onde-onde - Rp 800
  4. Lemper  - Rp 1250
  5. Risol - Rp 1500
  Silahkan pilih jajanan pasar kami yaa :)

  """)
  pesanan = input()
  if pesanan == "1":
    print("Kamu memesan Donat dengan harga Rp 1250, terima kasih sudah berbelanja!")
  elif pesanan == "2":
    print("Kamu memesan Bakwan dengan harga Rp 1000, terima kasih sudah berbelanja!")
  elif pesanan == "3":
    print("Kamu memesan Onde-onde dengan harga Rp 800, terima kasih sudah berbelanja!")
  elif pesanan == "4":
    print("Kamu memesan Lemper dengan harga Rp 1250, terima kasih sudah berbelanja!")
  elif pesanan == "5":
    print("Kamu memesan Risol dengan harga Rp 1500, terima kasih sudah berbelanja!")
  elif pesanan == "cukup":
    print("Terima kasih sudah berbelanja jajanan pasar kami :)")
    break
  else:
    print("Wah, pesanan kamu tidak terdaftar silahkan pilih yang tersedia yaa")

